config/routes.rb
Rails.application.routes.draw do
# #new 
#   get "/landmarks/new", to: "landmarks#new", as: "new_landmarks"

# #create 
# post "/landmarks/create", to: "landmarks#create", as: "landmarks"
# #index
# get "/landmarks", to: "landmarks#index"

# #edit
# get "/landmarks/:id/edit", to: "landmarks#edit", as: "edit_landmark"

# #show
# get "/landmarks/:id", to: "landmarks#show", as: "landmark"

# #update
# patch "/landmarks/:id", to: "landmarks#update"

# #destroy 
# delete "/landmarks/:id", to: "landmarks#destroy", as: "destroy_landmark"

# longestname
get "/landmarks/longestname", to: "landmarks#longestname", as: "longestname"

resources :users, only: [:new, :create, :show]
resources :landmarks

 post  "/landmarks/search", to: "landmarks#search", as: "landmark_search"
resources :landmarks do 
  resources :reviews, only: [:new, :index, :show, :create,  :edit, :update, :destroy]
end 
resources :users do 
  resources :landmarks 
end 

get '/signup', to: 'sessions#signup', as: 'signup'
post '/signup', to: 'users#create'
get '/login', to: 'sessions#login', as: 'login'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#logout', as: 'logout'


#omniauth
get '/auth/google_oauth2/callback', to: 'sessions#google_login', as: 'auth_google_oauth2_callback'

root "application#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landmark.rb
class Landmark < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :users, through: :reviews
    

    validates :name, presence: true, uniqueness: true
    validates :city, presence: true
    validates :country, presence: true
    validates :description, presence: true

   
    scope :ordered_by_name, -> { order(name: :asc)}
    scope :search_by, ->(param, val){ where("#{param} LIKE ?", "%#{val}%")}
    scope :longestname, -> {order( "LENGTH(name)")}

end

app/models/review.rb
class Review < ApplicationRecord
  
    belongs_to :user, optional: true 
    belongs_to :landmark
    validates :review, presence: true
    
   
  
end

app/models/user.rb
class User < ApplicationRecord
   
    has_secure_password

    has_many :reviews
    has_many :landmarks, through: :reviews

    validates :username, presence: true, uniqueness: :true
    validates :email, presence: true, uniqueness: :true
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/landmark_controller.rb
class LandmarkController < ApplicationController
    before_action :find_landmark, only: [:show, :edit, :update, :destroy]

    def index 
        @landmarks = Landmark.all
    end 


    def new 
        @landmark = Landmark.new 
    end 


    def create
        @landmark = Landmark.new(landmark_params)
        if @landmark.save
            redirect_to landmark_path(@landmark)
        else 
            render :new 
        end 
    end 

    def update 
        @landmark.update(landmark_params)
        redirect_to landmark_path(@landmark)
    end 

    def destroy 
        @landmark.destroy
        redirect_to landmark_path
    end 

private

def find_landmark
    @landmark = Landmark.find_by(id: params[:id])
end 

def landmark_params
    params.require(:landmark).permit(:name, :city, :country, :description, :user_id, :review_id)
end 

end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
    before_action :find_landmark, only: [:show, :edit, :update,:destroy]
    before_action :logged_in

    def index 
        @landmarks = current_user.landmarks.ordered_by_name 

    end 


    def new 
        @landmark = Landmark.new
        @review = @landmark.reviews.new 
    end 

    def longestname
        @landmarks = Landmark.longestname.last 
    end 


    def create
        @landmark = current_user.landmarks.build(landmark_params)
        if @landmark.save 
            @review = @landmark.reviews.build(reviews_params)
            @review.user = current_user
           @review.save
           flash[:messages] = ["#{@landmark.name} was successfully created!"]
        redirect_to landmark_path(@landmark)
       
        else 
            flash[:messages] = @landmark.errors.full_messages
            render :new 
        end 
    end 

    def search
        @landmarks = Landmark.search_by("name", params[:name])
        render :index
    end

    # def update 
    #     @landmark.update(landmark_params)
    #     redirect_to landmark_path(@landmark)
    # end 

    # def destroy 
    #     @landmark.destroy
    #     redirect_to landmarks_path
    # end 

private

def find_landmark
    @landmark = Landmark.find_by(id: params[:id])
end 

def landmark_params
    params.require(:landmark).permit(:name, :city, :country, :description)
end 

def reviews_params 
    params.require(:review).permit(:review, :landmark_id, :user_id)
end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_landmark
    before_action :logged_in
    
    def new 
        @review = @landmark.reviews.new 
    end 

    def create
        @review = Review.create(reviews_params)
        @review.landmark = @landmark
        if @review.save
            flash[:messages] = ["Review has been added"]
        redirect_to landmark_reviews_path(@review.landmark)
        else
            render :new 
        end 
    end 

    def index 
        @reviews = @landmark.reviews 
    end 

    def edit 
        @review = Review.find(params[:id])
        if @review.user != current_user
            redirect_to landmark_review_path(@review.landmark,@review)
        end
    end 

    def update
        @review = Review.find_by(id: params[:id])
        if @review.user == current_user
            @review.update(reviews_params)
            flash[:messages] = ["Review has been updated!"]
         redirect_to landmark_review_path
        else
            flash[:messages] = ["Oops something went wrong!"]
         redirect_to landmark_review_path(@review.landmark,@review)
        end
    end 

    def show 
        @review = @landmark.reviews.find_by(id: params[:id])
    end 


    def destroy
        @review = Review.find_by(id: params[:id])
        if @review.user == current_user
           @review.destroy 
           redirect_to landmark_reviews_path
        else 
            flash[:messages] = @review.errors.full_messages
            redirect_to landmark_review_path(@review.landmark,@review)
        end 
    end 

    private

    def reviews_params 
        
    params.require(:review).permit(:review, :landmark_id, :user_id)
    end 

    def find_landmark 
     @landmark = Landmark.find_by(id: params[:landmark_id])
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def signup 
      @user = User.new
      render :signup
    end 
  
    def login
        @user = User.new
      end
    
      def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          flash[:message] = @user.error.full_messages
          redirect_to login_path
        end
      end
    
      def logout
        session.clear
        redirect_to root_path
      end

      def google_login
        user_email = request.env['omniauth.auth']['info']['email']
        user_name = request.env['omniauth.auth']['info']['name']
        @user = User.find_or_create_by(email: user_email) do |user|
          user.username = user_name
          user.password = SecureRandom.hex
        end
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:messages] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end 
    
    def logged_in
    unless current_user 
        redirect_to login_path
      end 
    end

    
    def authenticate
        if !logged_in?
        redirect_to login_path 
        end 
     end 
end

app/helpers/landmark_helper.rb
module LandmarkHelper
    def all_landmarks 
        Landmark.all.ordered_by_name
    
    end 

  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/home.html.erb
<h1>Home</h1>
  
  <%= link_to "Signup", signup_path %>
  <%= link_to "Login", login_path %>
 

app/views/landmark/show.html.erb
<h1><%= @landmak.name%></h1>
<p><%= @landmak.city%><p>
<p><%= @landmak.country%><p>
<h3><%= @landmak.description%></h3>

<%= button_to "Destroy Landmark", delete_landmark_path(@landmark), method: :delete %>

app/views/landmarks/index.html.erb
<%= form_with url: landmark_search_path, local: true do |form| %>
    Find Landmark  <%=  form.text_field :name %>
    <%= form.submit "Search" %>
  <% end %>

  
<h2>All Landmarks: </h2>

<ul class="landmarks">
<% all_landmarks.each do |landmark|%>
    <h4><%= link_to landmark.name, landmark_path(landmark)%></h4>
<%end%>
</ul>
<br>

<br>
 
<h2><%= @current_user.username %>'s Landmarks:<h2>

<% if @current_user && @landmarks.empty? %>
    <p> Your Landmark's list is empty!</p> 
<% else %>
    <% @landmarks.each do |l|%>
        <h4><%= link_to l.name, landmark_path(l)%></h4>
    <%end%> 
<%end%>




<%= button_to "Profile", user_path(current_user), method: :get %>

app/views/landmarks/longestname.html.erb
<h1><%= @landmarks.name %></h1>

app/views/landmarks/new.html.erb
<%= render "partials/form", title:  "Create a Landmark", path: landmarks_path, method: :post%>

app/views/landmarks/show.html.erb
<label>Landmark:</label>


<h3>Landmark Name: <%=@landmark.name %></h3>
<h3>Landmark City: <%= @landmark.city %><h3>
<h3>Landmark Country: <%= @landmark.country %><h3>
<h3>Landmark Description: <%= @landmark.description%></h3>




<%= button_to "create a review", new_landmark_review_path(@landmark), method: :get %>

<%= button_to "Landmark's Reviews", landmark_reviews_path(@landmark), method: :get %>

<%= button_to "Landmarks", landmarks_path, method: :get %>

<%= button_to "Profile", user_path(current_user), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandmarkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body

  <div>
  <% flash[:messages]&.each do |message| %>
    <p class="flash-error"><%= message %></p>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>

app/views/partials/_errors.html.erb
<ul class="errors-list">
<% @landmark&.errors.full_messages.each do |err| %>
  <li><%= err %></li>
<% end %>
</ul>

app/views/partials/_form.html.erb
<h1><%= title %></h1>


<%= form_with url: path, method: method, local: true  do |f|%>
     
   <%= render "partials/errors" %>

 <%= f.fields_for @landmark do |l|%>
    
    <label> Name:</label><br>
       <%= l.text_field  :name %><br>

    <label> city:</label><br>
    <%= l.text_field  :city %><br>

    <label>Country:</label><br>
    <%= l.text_field :country %><br>

    <label> Description: </label><br>
    <%= l.text_area :description %><br> 
<%end%>
    <% if @review %>
     <%=  f.fields_for @review do |r| %>
        
        <label> Review: </label><br>
        <%= r.text_area :review %><br> 
     <%end%>
   <%end%>
    <%= f.submit %>
<%end%>

<%= button_to "Profile", user_path(current_user), method: :get %>

app/views/partials/_reviews.html.erb
<%= form_for @review, url: path, method: method do |f|%>

    <label> Review: </label><br>
    <%= f.text_area :review %><br> 

    <%= f.submit button_text %>

<%end%>

<%=button_to "Profile", user_path(current_user), method: :get %>

app/views/reviews/edit.html.erb
<%= render "partials/reviews", button_text: "Update", path: landmark_review_path(@landmark), method: :patch %>

<%= button_to "Destroy Review", landmark_review_path(@landmark), method: :delete %>

app/views/reviews/index.html.erb
<h1><%= @landmark.name %> Reviews </h1>

<% @reviews.each do |review|%>
  <h2><%= link_to "Reviews: #{review.landmark.name}",  landmark_review_path(review.landmark, review)%><h2>

<%end%>


<%= button_to "Profile", user_path(current_user), method: :get %>

app/views/reviews/new.html.erb
<%=render "partials/reviews", button_text: "Create Review", path: landmark_reviews_path(@landmark), method: :post %>

app/views/reviews/show.html.erb
<h2>Landmark Name: <%= @landmark.name%></h2>

<h2> Review: <%= @review.review%></h2>



<%= button_to "Profile", user_path(current_user), method: :get %>

<% if @review.user == current_user %>
<%= button_to "Edit Review", edit_landmark_review_path(@landmark,@review), method: :get %>
<% end %>

<%= button_to "Landmark's Reviews", landmark_reviews_path(@landmark), method: :get %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %>!</h1>

<%= button_to " Your landmarks", landmarks_path, method: :get %>
<%= button_to "Create landmark", new_landmark_path, method: :get %>


<%= link_to "Logout", logout_path, method: :delete %>